/** Mirrors backend `gameIds` in lib/games.js — labels for UI fallback. */
export const gameIds = {
  red: 1,
  blue: 2,
  yellow: 3,
  gold: 4,
  silver: 5,
  crystal: 6,
  ruby: 7,
  sapphire: 8,
  emerald: 9,
  firered: 10,
  leafgreen: 11,
  diamond: 12,
  pearl: 13,
  platinum: 14,
  heartgold: 15,
  soulsilver: 16,
  black: 17,
  white: 18,
  black2: 19,
  white2: 20,
  x: 21,
  y: 22,
  alphasapphire: 23,
  omegaruby: 24,
  sun: 25,
  moon: 26,
  ultrasun: 27,
  ultramoon: 28,
  letsgo: 29,
  sword: 30,
  shield: 31,
  scarlet: 32,
  violet: 33,
  legendsarceus: 34,
  legendsza: 35,
  brilliantdiamond: 36,
  shiningpearl: 37,
}

export const gameLabels = {
  [gameIds.red]: 'Pokémon Red',
  [gameIds.blue]: 'Pokémon Blue',
  [gameIds.yellow]: 'Pokémon Yellow',
  [gameIds.gold]: 'Pokémon Gold',
  [gameIds.silver]: 'Pokémon Silver',
  [gameIds.crystal]: 'Pokémon Crystal',
  [gameIds.ruby]: 'Pokémon Ruby',
  [gameIds.sapphire]: 'Pokémon Sapphire',
  [gameIds.emerald]: 'Pokémon Emerald',
  [gameIds.firered]: 'Pokémon FireRed',
  [gameIds.leafgreen]: 'Pokémon LeafGreen',
  [gameIds.diamond]: 'Pokémon Diamond',
  [gameIds.pearl]: 'Pokémon Pearl',
  [gameIds.platinum]: 'Pokémon Platinum',
  [gameIds.heartgold]: 'Pokémon HeartGold',
  [gameIds.soulsilver]: 'Pokémon SoulSilver',
  [gameIds.black]: 'Pokémon Black',
  [gameIds.white]: 'Pokémon White',
  [gameIds.black2]: 'Pokémon Black 2',
  [gameIds.white2]: 'Pokémon White 2',
  [gameIds.x]: 'Pokémon X',
  [gameIds.y]: 'Pokémon Y',
  [gameIds.alphasapphire]: 'Pokémon Alpha Sapphire',
  [gameIds.omegaruby]: 'Pokémon Omega Ruby',
  [gameIds.sun]: 'Pokémon Sun',
  [gameIds.moon]: 'Pokémon Moon',
  [gameIds.ultrasun]: 'Pokémon Ultra Sun',
  [gameIds.ultramoon]: 'Pokémon Ultra Moon',
  [gameIds.letsgo]: "Pokémon Let's Go",
  [gameIds.sword]: 'Pokémon Sword',
  [gameIds.shield]: 'Pokémon Shield',
  [gameIds.scarlet]: 'Pokémon Scarlet',
  [gameIds.violet]: 'Pokémon Violet',
  [gameIds.legendsarceus]: 'Pokémon Legends: Arceus',
  [gameIds.legendsza]: 'Pokémon Legends: Z-A',
  [gameIds.brilliantdiamond]: 'Pokémon Brilliant Diamond',
  [gameIds.shiningpearl]: 'Pokémon Shining Pearl',
}

export const gameGenerations = {
  [gameIds.red]: 1,
  [gameIds.blue]: 1,
  [gameIds.yellow]: 1,
  [gameIds.gold]: 2,
  [gameIds.silver]: 2,
  [gameIds.crystal]: 2,
  [gameIds.ruby]: 3,
  [gameIds.sapphire]: 3,
  [gameIds.emerald]: 3,
  [gameIds.firered]: 3,
  [gameIds.leafgreen]: 3,
  [gameIds.diamond]: 4,
  [gameIds.pearl]: 4,
  [gameIds.platinum]: 4,
  [gameIds.heartgold]: 4,
  [gameIds.soulsilver]: 4,
  [gameIds.black]: 5,
  [gameIds.white]: 5,
  [gameIds.black2]: 5,
  [gameIds.white2]: 5,
  [gameIds.x]: 6,
  [gameIds.y]: 6,
  [gameIds.omegaruby]: 6,
  [gameIds.alphasapphire]: 6,
  [gameIds.sun]: 7,
  [gameIds.moon]: 7,
  [gameIds.ultrasun]: 7,
  [gameIds.ultramoon]: 7,
  [gameIds.letsgo]: 7,
  [gameIds.sword]: 8,
  [gameIds.shield]: 8,
  [gameIds.legendsarceus]: 8,
  [gameIds.brilliantdiamond]: 8,
  [gameIds.shiningpearl]: 8,
  [gameIds.scarlet]: 9,
  [gameIds.violet]: 9,
  [gameIds.legendsza]: 9,
}

export const fallbackGames = Object.entries(gameLabels).map(([id, label]) => ({
  id: Number(id),
  label,
  generation: gameGenerations[Number(id)],
}))

/** Games shown before /api/games loads. */
export const supportedGames = fallbackGames

export function formatGame(gameId) {
  return gameLabels[Number(gameId)] ?? `Game ${gameId}`
}

export function generationForGame(gameId) {
  return gameGenerations[Number(gameId)] ?? 1
}
