/** Mirrors backend `gameIds` in models/Run.js — labels for UI. */
export const gameIds = {
  red: 1,
  blue: 2,
  yellow: 3,
  gold: 4,
  silver: 5,
  crystal: 6,
  ruby: 7,
  sapphire: 8,
  emerald: 9,
  firered: 10,
  leafgreen: 11,
  diamond: 12,
  pearl: 13,
  platinum: 14,
  heartgold: 15,
  soulsilver: 16,
  black: 17,
  white: 18,
  black2: 19,
  white2: 20,
  x: 21,
  y: 22,
  alphasapphire: 23,
  omegaruby: 24,
  sun: 25,
  moon: 26,
  ultrasun: 27,
  ultramoon: 28,
  letsgo: 29,
  sword: 30,
  shield: 31,
  scarlet: 32,
  violet: 33,
  legendsarceus: 34,
  legendsza: 35,
}

export const gameLabels = {
  [gameIds.red]: 'Pokémon Red',
  [gameIds.blue]: 'Pokémon Blue',
  [gameIds.yellow]: 'Pokémon Yellow',
  [gameIds.gold]: 'Pokémon Gold',
  [gameIds.silver]: 'Pokémon Silver',
  [gameIds.crystal]: 'Pokémon Crystal',
  [gameIds.ruby]: 'Pokémon Ruby',
  [gameIds.sapphire]: 'Pokémon Sapphire',
  [gameIds.emerald]: 'Pokémon Emerald',
  [gameIds.firered]: 'Pokémon FireRed',
  [gameIds.leafgreen]: 'Pokémon LeafGreen',
  [gameIds.diamond]: 'Pokémon Diamond',
  [gameIds.pearl]: 'Pokémon Pearl',
  [gameIds.platinum]: 'Pokémon Platinum',
  [gameIds.heartgold]: 'Pokémon HeartGold',
  [gameIds.soulsilver]: 'Pokémon SoulSilver',
  [gameIds.black]: 'Pokémon Black',
  [gameIds.white]: 'Pokémon White',
  [gameIds.black2]: 'Pokémon Black 2',
  [gameIds.white2]: 'Pokémon White 2',
  [gameIds.x]: 'Pokémon X',
  [gameIds.y]: 'Pokémon Y',
  [gameIds.alphasapphire]: 'Pokémon Alpha Sapphire',
  [gameIds.omegaruby]: 'Pokémon Omega Ruby',
  [gameIds.sun]: 'Pokémon Sun',
  [gameIds.moon]: 'Pokémon Moon',
  [gameIds.ultrasun]: 'Pokémon Ultra Sun',
  [gameIds.ultramoon]: 'Pokémon Ultra Moon',
  [gameIds.letsgo]: "Pokémon Let's Go",
  [gameIds.sword]: 'Pokémon Sword',
  [gameIds.shield]: 'Pokémon Shield',
  [gameIds.scarlet]: 'Pokémon Scarlet',
  [gameIds.violet]: 'Pokémon Violet',
  [gameIds.legendsarceus]: 'Pokémon Legends: Arceus',
  [gameIds.legendsza]: 'Pokémon Legends: Z-A',
}

/** Games with route/reference data seeded today. */
export const supportedGames = [
  { id: gameIds.red, label: gameLabels[gameIds.red] },
  { id: gameIds.blue, label: gameLabels[gameIds.blue] },
]

export function formatGame(gameId) {
  return gameLabels[Number(gameId)] ?? `Game ${gameId}`
}
