/** Canonical mainline game catalog. Numeric ids are stable and stored on runs. */
export const gameIds = {
  red: 1,
  blue: 2,
  yellow: 3,
  gold: 4,
  silver: 5,
  crystal: 6,
  ruby: 7,
  sapphire: 8,
  emerald: 9,
  firered: 10,
  leafgreen: 11,
  diamond: 12,
  pearl: 13,
  platinum: 14,
  heartgold: 15,
  soulsilver: 16,
  black: 17,
  white: 18,
  black2: 19,
  white2: 20,
  x: 21,
  y: 22,
  alphasapphire: 23,
  omegaruby: 24,
  sun: 25,
  moon: 26,
  ultrasun: 27,
  ultramoon: 28,
  letsgo: 29,
  sword: 30,
  shield: 31,
  scarlet: 32,
  violet: 33,
  legendsarceus: 34,
  legendsza: 35,
  brilliantdiamond: 36,
  shiningpearl: 37,
}

export const GAMES = [
  { id: gameIds.red, slug: 'red', label: 'Pokémon Red', generation: 1 },
  { id: gameIds.blue, slug: 'blue', label: 'Pokémon Blue', generation: 1 },
  { id: gameIds.yellow, slug: 'yellow', label: 'Pokémon Yellow', generation: 1 },
  { id: gameIds.gold, slug: 'gold', label: 'Pokémon Gold', generation: 2 },
  { id: gameIds.silver, slug: 'silver', label: 'Pokémon Silver', generation: 2 },
  { id: gameIds.crystal, slug: 'crystal', label: 'Pokémon Crystal', generation: 2 },
  { id: gameIds.ruby, slug: 'ruby', label: 'Pokémon Ruby', generation: 3 },
  { id: gameIds.sapphire, slug: 'sapphire', label: 'Pokémon Sapphire', generation: 3 },
  { id: gameIds.emerald, slug: 'emerald', label: 'Pokémon Emerald', generation: 3 },
  { id: gameIds.firered, slug: 'firered', label: 'Pokémon FireRed', generation: 3 },
  { id: gameIds.leafgreen, slug: 'leafgreen', label: 'Pokémon LeafGreen', generation: 3 },
  { id: gameIds.diamond, slug: 'diamond', label: 'Pokémon Diamond', generation: 4 },
  { id: gameIds.pearl, slug: 'pearl', label: 'Pokémon Pearl', generation: 4 },
  { id: gameIds.platinum, slug: 'platinum', label: 'Pokémon Platinum', generation: 4 },
  { id: gameIds.heartgold, slug: 'heartgold', label: 'Pokémon HeartGold', generation: 4 },
  { id: gameIds.soulsilver, slug: 'soulsilver', label: 'Pokémon SoulSilver', generation: 4 },
  { id: gameIds.black, slug: 'black', label: 'Pokémon Black', generation: 5 },
  { id: gameIds.white, slug: 'white', label: 'Pokémon White', generation: 5 },
  { id: gameIds.black2, slug: 'black2', label: 'Pokémon Black 2', generation: 5 },
  { id: gameIds.white2, slug: 'white2', label: 'Pokémon White 2', generation: 5 },
  { id: gameIds.x, slug: 'x', label: 'Pokémon X', generation: 6 },
  { id: gameIds.y, slug: 'y', label: 'Pokémon Y', generation: 6 },
  { id: gameIds.omegaruby, slug: 'omegaruby', label: 'Pokémon Omega Ruby', generation: 6 },
  { id: gameIds.alphasapphire, slug: 'alphasapphire', label: 'Pokémon Alpha Sapphire', generation: 6 },
  { id: gameIds.sun, slug: 'sun', label: 'Pokémon Sun', generation: 7 },
  { id: gameIds.moon, slug: 'moon', label: 'Pokémon Moon', generation: 7 },
  { id: gameIds.ultrasun, slug: 'ultrasun', label: 'Pokémon Ultra Sun', generation: 7 },
  { id: gameIds.ultramoon, slug: 'ultramoon', label: 'Pokémon Ultra Moon', generation: 7 },
  { id: gameIds.letsgo, slug: 'letsgo', label: "Pokémon Let's Go", generation: 7 },
  { id: gameIds.sword, slug: 'sword', label: 'Pokémon Sword', generation: 8 },
  { id: gameIds.shield, slug: 'shield', label: 'Pokémon Shield', generation: 8 },
  { id: gameIds.legendsarceus, slug: 'legendsarceus', label: 'Pokémon Legends: Arceus', generation: 8 },
  { id: gameIds.brilliantdiamond, slug: 'brilliantdiamond', label: 'Pokémon Brilliant Diamond', generation: 8 },
  { id: gameIds.shiningpearl, slug: 'shiningpearl', label: 'Pokémon Shining Pearl', generation: 8 },
  { id: gameIds.scarlet, slug: 'scarlet', label: 'Pokémon Scarlet', generation: 9 },
  { id: gameIds.violet, slug: 'violet', label: 'Pokémon Violet', generation: 9 },
  { id: gameIds.legendsza, slug: 'legendsza', label: 'Pokémon Legends: Z-A', generation: 9 },
]

export const gameById = new Map(GAMES.map((game) => [game.id, game]))

export function getGame(gameId) {
  return gameById.get(Number(gameId)) ?? null
}

export function generationForGame(gameId) {
  return getGame(gameId)?.generation ?? null
}
